- name: Update server1
  hosts: server1
  vars_files:
    - vars/server1_pass.yml
  roles:
    - { role: apt_update, tags: [apt_update] }

- name: Create some file
  hosts: server2
  roles: 
    - { role: create_some_file, tags: [create_file] } 
